export const AREAS = [
  {
    key: 1,
    name: 'Eldorado Canyon State Park',
    latitude: 39.9322,
    longitude: -105.2716,
    parent_key: null,
    description:
      'One of the premier climbing destinations in the country, featuring steep granite walls and world-class bouldering problems in a scenic canyon outside Boulder.',
  },
  {
    key: 2,
    name: 'Flagstaff Mountain',
    latitude: 39.9969,
    longitude: -105.2863,
    parent_key: null,
    description:
      'Historic bouldering area above Boulder with hundreds of problems on Fountain sandstone, ranging from beginner slabs to elite dynos.',
  },
  {
    key: 3,
    name: 'The Flatirons',
    latitude: 39.9997,
    longitude: -105.2919,
    parent_key: null,
    description:
      'Iconic tilted sandstone slabs rising above Boulder, with scattered bouldering at the base of the formations.',
  },
  {
    key: 4,
    name: 'Lumpy Ridge',
    latitude: 40.3977,
    longitude: -105.5244,
    parent_key: null,
    description:
      "Classic granite domes inside Rocky Mountain National Park, offering bouldering at elevation with stunning alpine scenery.",
  },
  {
    key: 5,
    name: 'Clear Creek Canyon',
    latitude: 39.7434,
    longitude: -105.3106,
    parent_key: null,
    description:
      'Steep sport climbing and quality bouldering on gneiss and schist along a rushing creek corridor west of Golden.',
  },
  {
    key: 6,
    name: 'Castlewood Canyon State Park',
    latitude: 39.3833,
    longitude: -104.7500,
    parent_key: null,
    description:
      'Conglomerate bouldering on the edge of the prairie south of Denver, sheltered from wind and often climbable when conditions elsewhere are too cold or wet.',
  },
  {
    key: 7,
    name: 'Horsetooth Reservoir',
    latitude: 40.5572,
    longitude: -105.1695,
    parent_key: null,
    description:
      'World-famous bouldering destination near Fort Collins with hundreds of sandstone problems that drew John Gill in the 1950s. Steep, powerful, and historic.',
  },
  {
    key: 8,
    name: 'Mount Evans Wilderness',
    latitude: 39.5883,
    longitude: -105.6438,
    parent_key: null,
    description:
      "High-alpine bouldering above 11,000 feet on perfect granite near one of the highest paved roads in North America. Short window due to snow.",
  },
]

export const BOULDERS = [
  // Eldorado Canyon (area_key: 1)
  {
    key: 1,
    name: 'The Blob',
    source_uuid: 'mp-eldo-blob',
    grade_v: 'V4',
    grade_font: '6B+',
    latitude: 39.9325,
    longitude: -105.2724,
    area_key: 1,
    is_boulder: true,
    description:
      'A classic Eldorado warm-up on textured granite. Sloping holds demand precise footwork and commitment. Spicy topout.',
    youtube_ids: ['dQw4w9WgXcQ', 'vt1Pwfss5B0'],
  },
  {
    key: 2,
    name: 'Gill Egg',
    source_uuid: 'mp-eldo-gill-egg',
    grade_v: 'V6',
    grade_font: '7A',
    latitude: 39.9319,
    longitude: -105.2720,
    area_key: 1,
    is_boulder: true,
    description:
      'John Gill himself put up this overhung egg-shaped boulder. Crimpy and powerful, with a powerful deadpoint to a sloper.',
    youtube_ids: [],
  },
  {
    key: 3,
    name: 'Mars Rock Direct',
    source_uuid: 'mp-eldo-mars',
    grade_v: 'V8',
    grade_font: '7B+',
    latitude: 39.9330,
    longitude: -105.2710,
    area_key: 1,
    is_boulder: true,
    description:
      'Technical face climbing on Mars-red granite, requiring body tension and precision on small feet.',
    youtube_ids: [],
  },
  {
    key: 4,
    name: 'Bastille Egg',
    source_uuid: 'mp-eldo-bastille-egg',
    grade_v: 'V3',
    grade_font: '6A+',
    latitude: 39.9335,
    longitude: -105.2730,
    area_key: 1,
    is_boulder: true,
    description:
      'Accessible moderate near the Bastille formation. Good holds and a rewarding highball finish.',
    youtube_ids: [],
  },

  // Flagstaff Mountain (area_key: 2)
  {
    key: 5,
    name: 'The Prow',
    source_uuid: 'mp-flag-prow',
    grade_v: 'V8',
    grade_font: '7B+',
    latitude: 39.9972,
    longitude: -105.2870,
    area_key: 2,
    is_boulder: true,
    description:
      'A Flagstaff testpiece — a clean arête on perfect sandstone with a V2 start that blossoms into powerful upper moves. Classic.',
    youtube_ids: ['L_jWHffIx5E'],
  },
  {
    key: 6,
    name: 'Animal Chin',
    source_uuid: 'mp-flag-animal-chin',
    grade_v: 'V6',
    grade_font: '7A',
    latitude: 39.9968,
    longitude: -105.2866,
    area_key: 2,
    is_boulder: true,
    description:
      "Continuous movement on crimps and slopers. Named after the Bones Brigade. Don't give up.",
    youtube_ids: [],
  },
  {
    key: 7,
    name: 'Royal Arch Area',
    source_uuid: 'mp-flag-royal-arch',
    grade_v: 'V4',
    grade_font: '6B+',
    latitude: 39.9975,
    longitude: -105.2875,
    area_key: 2,
    is_boulder: true,
    description:
      'A cluster of quality moderate problems with good landings, near the Royal Arch trail junction.',
    youtube_ids: [],
  },

  // Flatirons (area_key: 3)
  {
    key: 8,
    name: 'The Egg',
    source_uuid: 'mp-flat-egg',
    grade_v: 'V0',
    grade_font: '4',
    latitude: 40.0002,
    longitude: -105.2930,
    area_key: 3,
    is_boulder: true,
    description:
      'Perfect introductory slab boulder. Textbook foot smearing on friction. Great for kids or anyone getting outdoors for the first time.',
    youtube_ids: [],
  },
  {
    key: 9,
    name: 'Seal Rock',
    source_uuid: 'mp-flat-seal',
    grade_v: 'V2',
    grade_font: '5+',
    latitude: 39.9995,
    longitude: -105.2925,
    area_key: 3,
    is_boulder: true,
    description:
      'Sloping, balancey movement on a rounded boulder. Multiple eliminate and linkup variations keep it interesting.',
    youtube_ids: [],
  },

  // Lumpy Ridge (area_key: 4)
  {
    key: 10,
    name: 'Book Blocks',
    source_uuid: 'mp-lumpy-book',
    grade_v: 'V3',
    grade_font: '6A+',
    latitude: 40.3982,
    longitude: -105.5250,
    area_key: 4,
    is_boulder: true,
    description:
      'Highball granite bouldering with book-shaped features. Stellar rock quality and views of the Twin Owls.',
    youtube_ids: [],
  },
  {
    key: 11,
    name: 'Twin Owls Traverse',
    source_uuid: 'mp-lumpy-owls',
    grade_v: 'V5',
    grade_font: '6C+',
    latitude: 40.3975,
    longitude: -105.5248,
    area_key: 4,
    is_boulder: true,
    description:
      'An endurance traverse beneath the iconic Twin Owls formation. Pump-intensive and sequency on good granite.',
    youtube_ids: [],
  },

  // Clear Creek Canyon (area_key: 5)
  {
    key: 12,
    name: "Crystal Wall",
    source_uuid: 'mp-cc-crystal',
    grade_v: 'V5',
    grade_font: '6C+',
    latitude: 39.7440,
    longitude: -105.3115,
    area_key: 5,
    is_boulder: true,
    description:
      'Quartzite face with glittery crystal holds. A technical gem tucked above the creek bed.',
    youtube_ids: [],
  },
  {
    key: 13,
    name: "Ship's Prow",
    source_uuid: 'mp-cc-ships',
    grade_v: 'V3',
    grade_font: '6A+',
    latitude: 39.7438,
    longitude: -105.3110,
    area_key: 5,
    is_boulder: true,
    description:
      'Prow-shaped boulder above the creek. Clean line, solid moves, good landing. A crowd favorite.',
    youtube_ids: [],
  },

  // Castlewood Canyon (area_key: 6)
  {
    key: 14,
    name: 'Narrows Traverse',
    source_uuid: 'mp-castle-narrows',
    grade_v: 'V4',
    grade_font: '6B+',
    latitude: 39.3840,
    longitude: -104.7508,
    area_key: 6,
    is_boulder: true,
    description:
      'Long conglomerate traverse inside the narrows of the canyon. The pebble holds are surprisingly positive.',
    youtube_ids: [],
  },
  {
    key: 15,
    name: 'Dam Wall Problem',
    source_uuid: 'mp-castle-dam',
    grade_v: 'V6',
    grade_font: '7A',
    latitude: 39.3845,
    longitude: -104.7502,
    area_key: 6,
    is_boulder: true,
    description:
      'Overhung conglomerate near the old dam ruins. Strong and pumpy for a short problem. The rock is covered in huge pebbles.',
    youtube_ids: [],
  },

  // Horsetooth (area_key: 7)
  {
    key: 16,
    name: 'Gill Crack',
    source_uuid: 'mp-ht-gill-crack',
    grade_v: 'V3',
    grade_font: '6A+',
    latitude: 40.5580,
    longitude: -105.1700,
    area_key: 7,
    is_boulder: true,
    description:
      "John Gill's original test piece at Horsetooth. A short, steep crack on Fountain sandstone — and a piece of climbing history.",
    youtube_ids: [],
  },
  {
    key: 17,
    name: 'Eliminator',
    source_uuid: 'mp-ht-eliminator',
    grade_v: 'V9',
    grade_font: '7C',
    latitude: 40.5578,
    longitude: -105.1695,
    area_key: 7,
    is_boulder: true,
    description:
      'One of the most iconic boulder problems in the country. Roof to slab, massive reach, massive commitment. This is what Horsetooth is for.',
    youtube_ids: [],
  },

  // Mount Evans (area_key: 8)
  {
    key: 18,
    name: 'Echo Lake Block',
    source_uuid: 'mp-evans-echo',
    grade_v: 'V5',
    grade_font: '6C+',
    latitude: 39.5890,
    longitude: -105.6445,
    area_key: 8,
    is_boulder: true,
    description:
      'High-altitude granite bouldering above Echo Lake. The thin air is real; the moves are crimpy and technical.',
    youtube_ids: [],
  },
]

export const WEATHER = [
  {
    key: 1,
    area_key: 1,
    temperature: 72,
    precipitation: 0.05,
    cloud_cover: 28,
    humidity: 34,
    wind_speed: 7,
    climbability: 88,
    forecast_time: '2026-06-27T14:00:00Z',
    time_fetched: '2026-06-27T12:00:00Z',
    conditions: 'Partly Cloudy',
  },
  {
    key: 2,
    area_key: 2,
    temperature: 68,
    precipitation: 0.0,
    cloud_cover: 20,
    humidity: 29,
    wind_speed: 11,
    climbability: 91,
    forecast_time: '2026-06-27T14:00:00Z',
    time_fetched: '2026-06-27T12:00:00Z',
    conditions: 'Clear',
  },
  {
    key: 3,
    area_key: 3,
    temperature: 70,
    precipitation: 0.0,
    cloud_cover: 22,
    humidity: 31,
    wind_speed: 9,
    climbability: 90,
    forecast_time: '2026-06-27T14:00:00Z',
    time_fetched: '2026-06-27T12:00:00Z',
    conditions: 'Clear',
  },
  {
    key: 4,
    area_key: 4,
    temperature: 58,
    precipitation: 0.0,
    cloud_cover: 15,
    humidity: 25,
    wind_speed: 14,
    climbability: 85,
    forecast_time: '2026-06-27T14:00:00Z',
    time_fetched: '2026-06-27T12:00:00Z',
    conditions: 'Mostly Clear',
  },
  {
    key: 5,
    area_key: 5,
    temperature: 79,
    precipitation: 0.12,
    cloud_cover: 45,
    humidity: 42,
    wind_speed: 6,
    climbability: 65,
    forecast_time: '2026-06-27T14:00:00Z',
    time_fetched: '2026-06-27T12:00:00Z',
    conditions: 'Partly Cloudy',
  },
  {
    key: 6,
    area_key: 6,
    temperature: 82,
    precipitation: 0.0,
    cloud_cover: 10,
    humidity: 22,
    wind_speed: 4,
    climbability: 95,
    forecast_time: '2026-06-27T14:00:00Z',
    time_fetched: '2026-06-27T12:00:00Z',
    conditions: 'Sunny',
  },
  {
    key: 7,
    area_key: 7,
    temperature: 74,
    precipitation: 0.02,
    cloud_cover: 33,
    humidity: 37,
    wind_speed: 10,
    climbability: 84,
    forecast_time: '2026-06-27T14:00:00Z',
    time_fetched: '2026-06-27T12:00:00Z',
    conditions: 'Partly Cloudy',
  },
  {
    key: 8,
    area_key: 8,
    temperature: 52,
    precipitation: 0.3,
    cloud_cover: 70,
    humidity: 58,
    wind_speed: 18,
    climbability: 38,
    forecast_time: '2026-06-27T14:00:00Z',
    time_fetched: '2026-06-27T12:00:00Z',
    conditions: 'Overcast / Afternoon Storms',
  },
]
